### ISSUE TITLE
fix: Module '"@/components/ui/popover"' has no exported member 'PopoverAnchor

### ISSUE THREAD

**Issue by yeasin2002** [Balastrong/shadcn-autocomplete-demo#2]
Shadcn update I think and they do not provide PopoverAnchor things, 
Kindly update with current changes

![image](https://github.com/user-attachments/assets/18ad3081-8e44-4370-b2f7-ddbdb7331c8d)

**Comment by Balastrong** [comment]
Hey! Do you want to open a PR for that? :)

**Comment by genthalili** [comment]
You might need to update popover component and overwrite with the latest update from shadcn, that worked for me.

**Comment by yeasin2002** [comment]
> You might need to update popover component and overwrite with the latest update from shadcn, that worked for me.

What did you used instead of PopoverAnchor?

**Comment by genthalili** [comment]
I just ran : ``npx shadcn@latest add popover``, and then `y` (yes) to the question if you want to overwrite the file.

**Comment by yeasin2002** [comment]
> Hey! Do you want to open a PR for that? :)

Hopefully, Yes

**Comment by Balastrong** [comment]
@yeasin2002 feel free to open the PR whenever you have time, I'll be happy to review and merge it :D

**Comment by demenech** [comment]
I fixed this on a project by adding the following to `ui/popover.tsx`:

```typescript
const PopoverAnchor = PopoverPrimitive.PopoverAnchor;
export { Popover, PopoverTrigger, PopoverContent, PopoverAnchor };
```

**Comment by Balastrong** [comment]
I think the problem is on shadcn, have a look at the Popover component in the two different themes:

[Default (L31)](https://github.com/shadcn-ui/ui/blob/1081536246b44b6664f4c99bc3f1b3614e632841/apps/www/registry/default/ui/popover.tsx#L31):
```ts
export { Popover, PopoverTrigger, PopoverContent }
```

[New York (L33)](https://github.com/shadcn-ui/ui/blob/1081536246b44b6664f4c99bc3f1b3614e632841/apps/www/registry/new-york/ui/popover.tsx#L33):
```ts
export { Popover, PopoverTrigger, PopoverContent, PopoverAnchor }
```

---

If you're using the **Default theme** you need to add the `PopoverAnchor` export manually as @demenech mentioned in the previous comment, if you're on the New York theme it's already fine :)
